### ISSUE TITLE
Crash without any information

### ISSUE THREAD

**Issue by X-Filess** [gfto/tsdecrypt#12] opened 2017-12-13 12:44 UTC
Hello.

tsdecrypt crash on loading ...

$ ./tsdecrypt -s 192.168.10.20:3008 -U osc2 -P osc2 -B 0102030405060708091011121314 -c CONAX -A NEWCAMD -C 0x0B00 -1 10.10.10.10 -I 230.230.1.200:2234 -o 10.10.10.10 -O 230.230.1.200:3234
2017-12-13 12:30:57 | Syslog     : disabled
2017-12-13 12:30:57 | CA System  : CONAX | CAID: 0x0b00 (2816)
2017-12-13 12:30:57 | Input addr : udp://230.230.1.200:2234/
2017-12-13 12:30:57 | Input src  : 10.10.10.10
2017-12-13 12:30:57 | Output addr: udp://230.230.1.200:3234/
2017-12-13 12:30:57 | Output intf: 10.10.10.10 (IPv6 intf index:-1)
2017-12-13 12:30:57 | Output ttl : 1
2017-12-13 12:30:57 | Out filter : enabled (output only service related PIDs)
2017-12-13 12:30:57 | TS discont : report
2017-12-13 12:30:57 | Decoding   : threaded
2017-12-13 12:30:57 | CAMD proto : newcamd
2017-12-13 12:30:57 | CAMD addr  : 192.168.10.20:3008 (IPv4/IPv6)
2017-12-13 12:30:57 | CAMD user  : osc2
2017-12-13 12:30:57 | CAMD pass  : osc2
2017-12-13 12:30:57 | CAMD deskey: 0102030405060708091011121314
2017-12-13 12:30:57 | EMM process: No
2017-12-13 12:30:57 | ECM process: Yes
2017-12-13 12:30:57 | ECM report : 60 sec
2017-12-13 12:30:57 | CW warning : 60 sec
2017-12-13 12:30:57 | Start tsdecrypt v10.0 (v10.0-44-g4ecdc6d, libdvbcsa)
Segmentation fault (core dumped)
$ gdb tsdecrypt core 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from tsdecrypt...done.
[New LWP 25827]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tsdecrypt -s 192.168.10.20 3008 -U osc2 -P osc2 -B 01020304050607080910111213'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000041af85 in notify_func (ts=ts@entry=0x62bfa0 <ts>, sync_msg=sync_msg@entry=0, msg_id=msg_id@entry=0x4243fa "START", msg_text=msg_text@entry=0x7fff9b541110 "Starting tsdecrypt v10.0 (v10.0-44-g4ecdc6d, libdvbcsa)")
    at notify.c:188
188             if (ts->notify->notifications) {
(gdb) bt
#0  0x000000000041af85 in notify_func (ts=ts@entry=0x62bfa0 <ts>, sync_msg=sync_msg@entry=0, msg_id=msg_id@entry=0x4243fa "START", msg_text=msg_text@entry=0x7fff9b541110 "Starting tsdecrypt v10.0 (v10.0-44-g4ecdc6d, libdvbcsa)")
    at notify.c:188
#1  0x000000000041b223 in notify (ts=ts@entry=0x62bfa0 <ts>, msg_id=msg_id@entry=0x4243fa "START", text_fmt=text_fmt@entry=0x4243ee "Starting %s") at notify.c:212
#2  0x00000000004046b4 in main (argc=<optimized out>, argv=<optimized out>) at tsdecrypt.c:1013
(gdb)

please check it

**Comment by gfto** [comment] 2017-12-13 14:14
The problem is a bug that is seen only when you are not using --ident option.

I've fixed in the current master commit: b1eaec9c115ff5ac60845d8b446926d4474b0c95

so either update to current master or add --ident to your tsdecrypt options.

**Comment by gfto** [comment] 2017-12-13 14:14
The problem is a bug that is seen only when you are not using --ident option.

I've fixed in the current master commit: b1eaec9c115ff5ac60845d8b446926d4474b0c95

so either update to current master or add --ident to your tsdecrypt options.

**Closed by gfto** 2017-12-13 14:14 UTC
